feat(components): export Overlay and ToggleSwitch
camunda/camunda-modeler-plugin-helpers pull request #12
Opened 2021-10-29 09:31 UTC by smbea

- Export `Overlay` and `ToggleSwitch` (needed for the cloud-connect-plugin)

2021-10-29 09:52 UTC, barmac commented on components.js
> + * function CustomModal(props) {
```suggestion
 * function CustomOverlay(props) {
```

2021-10-29 10:07 UTC, pinussilvestrus commented on components.js
> +  export const ToggleSwitch = window.components.ToggleSwitch;
We do that with the toggle switch right now. Do we plan to do that with other form components as well? This way plugins don't have to define them on their own, e.g. https://github.com/camunda/cloud-connect-modeler-plugin/blob/master/src/components/CloudConnectPluginModal.js#L132-L160

Probably not part of this PR but something to consider when aligning all the form components.

2021-10-29 10:34 UTC, smbea commented on components.js
> +  export const ToggleSwitch = window.components.ToggleSwitch;
I might make sense to do so. We would avoid duplicating code and having to change it everywhere if we decide to alter something. But I agree that it should be a separate issue, since it is not pressing at the moment.

2021-10-29 14:32 UTC, barmac reviewed
What should happen if I use it in an old version of Camunda Modeler? I'd expect an error like we have in:
https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12/files#diff-9952085201d5294bbe13e9af4011a32c3534cf1cff58505c1a0ec59ac4a3757cR1-R3

2021-10-29 14:36 UTC, smbea commented
> What should happen if I use it in an old version of Camunda Modeler? I'd expect an error like we have in:
https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12/files#diff-9952085201d5294bbe13e9af4011a32c3534cf1cff58505c1a0ec59ac4a3757cR1-R3

@barmac I cannot see where the link is pointing too, but do you mean this?
```javascript
if (!window.components) {
  throw new Error('Not compatible with Camunda Modeler < 3.4');
}
```

Checking `if (!window.components.ToggleSwitch)`?

2021-10-29 14:41 UTC, barmac commented
Correct, this is the code I meant. Sorry for a bad link.

2021-10-29 14:42 UTC, barmac commented
I'd suggest to check what happens if I install the WIP Cloud Connect with the new components and then try to open Camunda Modeler v4.10.0. What errors can I see? What happens to the plugin?

2021-11-01 07:51 UTC, smbea commented
> I'd suggest to check what happens if I install the WIP Cloud Connect with the new components and then try to open Camunda Modeler v4.10.0. What errors can I see? What happens to the plugin?

@barmac The new plugin would break the modeler when the icon is clicked. But for the [compatibility matrix](https://docs.camunda.org/cawemo/latest/technical-guide/integrations/modeler/#compatibility) would be updated on the next release to signal so.

As far as this library goes, I tested with an older version of the modeler (which doesn't contain the components), and could not detect any visible errors. The app work as expected.

2021-11-01 14:18 UTC, nikku commented
The way we could accomplish https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12#issuecomment-954796682 is a wrapper function:

```javascript
export const ToggleSwitch = function(...args) {
  if (!window.components.ToggleSwitch) {
    // throw new error...
  } 
  
  return window.components.ToggleSwitch(...args);
}
```

That would follow the good practices we've established in this helper module.

2021-11-01 14:20 UTC, nikku requested changes
See my comment on ensuring improved backwards in-compatibility: https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12#issuecomment-956274139.

2021-11-01 14:21 UTC, nikku commented
Or, alternatively: 

```
export const ToggleSwitch = window.components.ToggleSwitch || UnsupportedComponent('4.12');
```

2021-11-01 14:37 UTC, smbea commented
> ```js
> export const ToggleSwitch = function(...args) {
>   if (!window.components.ToggleSwitch) {
>     // throw new error...
>   } 
>   
>   return window.components.ToggleSwitch(...args);
> }
> ```

I agree. I updated the exports to match this.

2021-11-01 15:10 UTC, nikku commented
@smbea Please see https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12/commits/579d45a92d2e7a5899cac04c98f738ca0783b1d9 which adds the simpler version I proposed [here](https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12#issuecomment-956277028).

2021-11-01 15:10 UTC, nikku commented
If that works for you I'm happy to give my :+1:.

2021-11-01 15:10 UTC, smbea commented
> @smbea Please see [579d45a](https://github.com/camunda/camunda-modeler-plugin-helpers/commit/579d45a92d2e7a5899cac04c98f738ca0783b1d9) which adds the simpler version I proposed [here](https://github.com/camunda/camunda-modeler-plugin-helpers/pull/12#issuecomment-956277028).

I like it. Much cleaner

2021-11-01 15:12 UTC, merged

2021-11-01 15:13 UTC, nikku commented
Let us release this one helper with another alpha tag and let's go!